services:
  postgres-test:
    image: postgres:16
    container_name: postgres-test
    environment:
      POSTGRES_DB: start-project-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  server-test:
    container_name: server-test
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - postgres-test
    stop_grace_period: 1s
    stop_signal: SIGKILL
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_NAME: start-project-test
      DB_USER: postgres
      DB_PASSWORD: postgres
